### ISSUE TITLE
Window Styles

### ISSUE THREAD

**Issue by Ron-Ldn** [Ron-Ldn/ExcelWizardLikeGUIs#1]
I have added a check box on the ribbon. If the box is ticked, then the "CreateParams" method override in the form will change some window styles.

I have tried "WS_EX_NOACTIVATE" (0x08000000). With this style, the 4th option (ShowDialog called from separate thread) allows you to select a range into Excel without having to activate Excel. 
Actually Excel remains activated all the time, which does seem to be like in the Bloomberg add-in.
Problem : if I start typing in the text box of the form, then Excel steels the focus and I end editing a cell !

**Comment by govert** [comment]
You might like to check with Spy++ what the window styles of the built-in 'Function Arguments' dialog is. I notice that as long as it is open, it remains the active window (both when selecting a range in Excel and when editing the formula in Excel).

**Comment by Ron-Ldn** [comment]
Good idea. Actually I used it with the Bloomberg add-in because it is closer to what I want. 
First remark : the GUI is running in the Excel main thread.

Here is what I saw for the styles.
Window Styles: 14000000
WS_VISIBLE
WS_CLIPSIBLINGS
WS_OVERLAPPED

Extended_Styles: 00000000
WS_EXT_LEFT
WS_EX_LTRREADING
WS_EX_RIGHTSCROLLBAR

I will try to apply the same and see what happens.

**Comment by govert** [comment]
In what respect is the Bloomberg one better than the built-in Function Arguments?

**Comment by Ron-Ldn** [comment]
You can keep working in Excel while the Bloomberg GUI is open, like if it was working in a separate thread. You can edit cell formulas, evaluate them, etc.
I was quite surprised to see that the window was hosted by the same thread. I will check a second time...

**Comment by Ron-Ldn** [comment]
Of course, applying the same styles to my form didn't work :(

**Comment by Ron-Ldn** [comment]
I noticed something interesting with Spy++: the parent window of the Bloomberg GUI is the active workbook.
If I close the workbook, then the GUI disappears. If there is no open workbook in the session, then the button in the ribbon to open the GUI does not do anything.

**Comment by govert** [comment]
With the built-in Function Arguments you can edit the formula while the dialog is open, and the arguments dialog responds as you go along. At no point is Excel the active window, but the formula editing can have the focus. As you change the formula (typing in the name of a function and then the opening bracket) the dialog changes shape and contents.

**Comment by govert** [comment]
What Excel version are you testing with? I have Excel 2013. The details of the windowing changed a lot in this version - workbooks are now in their own top-level windows. The built-in Function Arguments kind of anchors you to the workbook from here it came, which I find interesting.

**Comment by Ron-Ldn** [comment]
I never noticed that I could edit the formula in the formula bar when the "Function Arguments" window is open. I learn things about Excel every day !
The Bloomberg one is a bit different: not only you can edit the current formula, but you can also edit another cell. For instance, let's assume your formula is into A1, and you want to select B1 as the first input. You can actually edit B1 at the same time, without closing the GUI.
It is not intuitive for a function wizard, I think this is even completely useless, but the concept is powerful for other kind of helpers.
What I want in the end is a sophisticated window where you could select different ranges as input, and an output range where to apply the formula. I want the user to be able to change the destination, or even to insert the formula in different locations. This seems doable from what I see with the Bloomberg window.

**Comment by Ron-Ldn** [comment]
The Bloomberg add-in is present on a specific Bloomberg terminal, where only Excel 2010 is installed.
On my development PC, I have both Excel 2010 and 2013, but no Bloomberg.
