### ISSUE TITLE
Related links

### ISSUE THREAD

**Issue by govert** [Ron-Ldn/ExcelWizardLikeGUIs#2]
These are some possibly useful related projects, mainly focused on providing a RefEdit-like control:

* http://blogs.msdn.com/b/gabhan_berry/archive/2008/06/12/net-refedit-control.aspx
* http://www.codeproject.com/Articles/32805/RefEdit-Emulation-for-NET
* http://www.codeproject.com/Articles/34425/VS-NET-Excel-Addin-Refedit-Control

Also, the C API provides a dialog creation interface (SHOW.DIALOG) that allows you to add controls to a dialog, including adding a reference selector control. This snippet is a start: https://groups.google.com/forum/#!searchin/exceldna/show.dialog/exceldna/U6glMmn98KU/laRRDoSXo-4J Then the C API help file describes all the options.

**Comment by Ron-Ldn** [comment]
The first link is probably the most interesting, but the download is not available anymore :/
I have tried the solution with the Excel process handle, with no luck.

The 2 other links describe how to build the control but not what to do about the form itself. I am not sure that these people cared about my issues.

**Comment by Ron-Ldn** [comment]
Found an interesting link: http://stackoverflow.com/questions/3427696/windows-requires-a-click-to-activate-a-window-before-a-second-click-will-select

**Comment by govert** [comment]
That suggests that the WM_MOUSEACTIVATE result that Office returns swallows only the mouse down events.

**Comment by govert** [comment]
Yes - that's confirmed here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms645601(v=vs.85).aspx#_win32_Window_Activation

"By processing WM_MOUSEACTIVATE, a window can control whether the top-level window becomes the active window as a result of a mouse click, and whether the window that was clicked receives the subsequent **button-down** message. It does so by returning one of the following values after processing WM_MOUSEACTIVATE."
