### ISSUE TITLE
Mouse location ?

### ISSUE THREAD

**Issue by Ron-Ldn** [Ron-Ldn/ExcelWizardLikeGUIs#3]
Just to mention a dead-end !

I have tried working with mouse events in order to detect when the cursor is on the form or not. By combining with the ShowDialog method run from a separate thread, it was possible to enter the box and activate Excel automatically when moving the cursor outside the form.

Problem: what shall we do when the range address in populated within the box ? 
- Activate the form ? Then the user will have to re-activate Excel manually before changing the selection
- Activate Excel ? Then the user will have to re-activate the form before editing the address manually

I don't like any of these. That's not how Bloomberg works anyway.

**Comment by govert** [comment]
I don't understand what the activation has to do with the address population.

My understanding is now this:
The user clicks on Excel, and you want to immediately do a cell selection, or start a selection if the mouse button is still down. Excel must be swallowing the first mouse event. You could install a message handler in the Excel window(s), and pass through the mouse message after activation.

[Do you know if your Bloomberg works right on Excel 2013? It might not.]

**Comment by govert** [comment]
The window being deactivated by the mouse click will also get a WM_ACTIVATE message (with different parameters.)

Check this as a start: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646274%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 

There are some options related to WM_MOUSEACTIVATE that seems like clues: https://msdn.microsoft.com/en-us/library/windows/desktop/ms645612(v=vs.85).aspx

It might depend on Excel how the mouse click that does the activation is handled.
Not sure how one would interfere (safely).

**Comment by govert** [comment]
So maybe this: you hook the Excel message proc, capture WM_MOUSEACTIVATE and return MA_NOACTIVATE you should have Excel processing the mouse message without getting activated.

If you do hook the Excel messages, remember to remove the hook after your form closes - the .NET interop is slow enough to interfere with Excel if you leave the hook installed. (Otherwise you have to do it in native code.)

**Comment by govert** [comment]
So I conjecture that Excel is handling WM_MOUSEACTIVATE and returning MA_ACTIVATEANDEAT (Activates the window, and discards the mouse message.) This is not the default behaviour for windows. Compare with this:
* Open Notepad and type some stuff.
* Open Excel
* Arrange side-by-side
* Click on Excel so that it is active.
* Now click in the Notepad window, somewhere in the text - the window is activated and the cursor is placed in the text, where you clicked.
* Now click on Excel somewhere on the sheet. Excel is activated, but the mouse click is not further processed. You have to click again to select the cell.

So it looks like this is the behaviour explicitly chosen by Excel (and Word).
But you should be able to override it by hooking that message.

**Comment by Ron-Ldn** [comment]
You are right, other applications than Office allows you to select at the same time you re-activate the application. 
This even works with a child window of Excel. My add-in contains a tool window which can be opened from the ribbon and runs in the Excel thread. It is possible to select cells in one of its grid without having to click on it a fist time before.

I will give a try to your solution, it looks promising.

I did some more checks on the Bloomberg add-in:
- it is using the office interop assemblies. The version deployed to my Bloomberg terminal is 14. So I guess it wouldn't work with Excel 2013 anyway. I don't have any version of their add-in for Excel 2013, but since they had to rebuild it, they may have rewritten a lot.
- I told you that when a cell or the formula bar is in edit mode, the Bloomberg GUI is still available whereas my form is frozen. I tried another test: if a macro is running then the Bloomberg GUI is frozen. This confirms that it is running in the Excel thread, which I already saw through Spy++. I wonder how it is possible to edit a cell or the formula bar without holding the thread ?

**Comment by govert** [comment]
Using the Excel 2010 interop assembly does not imply any problem for running under Excel 2013. (The interop assembly just defines the COM interfaces, which are never supposed to change anyway.)

Editing the formula does not mean the thread is tied up in any way, though we've seen that the editing happens in a different 'window' (i.e. window message loop). I'm not sure why your form would lock up in those cases. The issue might relate to how the message loops defer to each other. When you say your form is frozen, do you mean it does not paint, does not respond to mouse messages, cannot get the keyboard focus?

**Comment by Ron-Ldn** [comment]
You can observe it with my first example "Call Show from Excel thread". If you click on the button, and then edit the formula bar in Excel, then the form cannot be selected with the mouse until you finished editing the formula bar, by escaping or entering.

I could live with that. But here is the exact use-case I want to address:
- my form contains a "RefEdit" like control where to set the first argument of the function
- the user wants to copy and paste the value contained in "A1", but not the cell address
- the user enters the formula, copies the value, and finally comes back to the form in order to paste
- the form does not respond because the user must first exist the formula edition

With the Bloomberg add-in, the form can be selected and modified while the formula is still in edit mode in Excel.

**Comment by Ron-Ldn** [comment]
I am quite struggling to understand how to hook the WM_MOUSEACTIVATE.
I managed to hook either WH_MOUSE or WH_MOUSE_LL. From the MSDN, I understand that WH_MOUSE is to hook the message after it has been posted, whereas WH_MOUSE_LL is to hook it before. Then I guess I should use WH_MOUSE_LL.
In both cases, the "wParam" of the MouseProc callback is 513 when I click in Excel. I assume that's where I should take action. But what action ?
I will keep digging, but if you have some directions to give me, it would help a lot.
Thanks

**Comment by govert** [comment]
I think you should figure out which window is getting WM_MOUSEACTIVATE. It really sounds like the message that controls the behaviour you see, and must be handled at some level.

**Comment by govert** [comment]
I can't remember the hierarchy, but it might not be the workbook window.

**Comment by govert** [comment]
In Spy++ I can see the WM_MOUSEACTIVATE message on the top-level window (the one with class  NetUIHWND). You can see the MA_ACTIVATEANDEAT result too.

**Comment by Ron-Ldn** [comment]
MA_ACTIVATEANDEAT discards the mousse message, so that's why it does not let you select.

I am still struggling to intercept the message. I am using SetWindowsHookEx, but the only way I managed to see the WM_MOUSEACTIVATE message was by hooking WH_CALLWNDPROC, which from my understanding does not allow you to change the result of the message.
I have tried hooking WH_MOUSE, but I don't see any WM_MOUSEACTIVATE coming. I can get WM_LBUTTONDOWN and WM_LBUTTONUP though.

**Comment by govert** [comment]
I think you want to install a message filter - that another option in SetWindowsHookEx.

If you push the hooking stuff you have now I can have a look tonight.

**Comment by govert** [comment]
Ah - the docs make it look like message filter will only work in some restricted cases - dialog, scroll bar etc.

**Comment by Ron-Ldn** [comment]
Yes I tried the message filter too with no more luck. I will commit my code with the different ways of hooking. It is quite quick and dirty but there is not a lot of code so it should be understandable.
The code is activated only when you launch the 4th button: "Call ShowDialog from separate thread".
You can activate or deactivate the hooks within the following code:

 if (xlThreadId != 0)
            {
                HookProc proc = MouseHookProc;
                //hHook = SetWindowsHookEx(WH_MOUSE_LL, proc, (IntPtr) 0, 0);
                hHook = SetWindowsHookEx(WH_MOUSE, proc, (IntPtr)0, xlThreadId);

                //HookProc proc = MsgProc;
                //hHook = SetWindowsHookEx(WH_GETMESSAGE, proc, (IntPtr)0, xlThreadId);

                //HookProc proc = CwpProc;
                //hHook = SetWindowsHookEx(WH_CALLWNDPROC, proc, (IntPtr)0, xlThreadId);
            }

Thanks a lot for your help.
